### PR TITLE
Decode request to json if Content-Type of request is application/json

### PR DESCRIPTION
**Pull request by cve**

### CODE REVIEW

**Comment by chalasr** [comment]
Thank you @cve

**Comment by cve** [comment]
Hmm, I see that for /register it works, but for /login the Symfony's security component takes action which does not decode appliaction/json request... one of workarounds to this is using https://github.com/qandidate-labs/symfony-json-request-transformer I see

**Comment by cve** [comment]
So... maybe a better aproach will be leave that responsibility (decoding appropriate request format [there is not only application/json but xml etc...]) outside of this bundle and note that in readme?

FOSRest has it's own decoder, ApiPlatform doesn't (I'm not sure), so for cases like that I can use https://github.com/qandidate-labs/symfony-json-request-transformer third party transformer...

**Comment by chalasr** [comment]
@cve JSON is a very common format for getting a JWT so IMHO we should be able to ensure that a request content of this type will be decoded as well as a form-data one.

There is a work in progress for providing a Symfony built-in JSON authentication listener (see https://github.com/symfony/symfony/pull/18952) which should greatly help on this in the future.
But for now, I'm 👍  for ensuring this by our side. 

Adding `qandidate/symfony-json-request-transformer` as a dependency is not be a problem to me, I'm just afraid that it converts all incoming requests (included the ones out of this bundle), that may be too much.

A solution would be to require it then override it with a check such as
```php
public function onKernelRequest(GetResponseEvent $event)
{
    if (0 === strpos($event->getRequest()->attributes->get('_route'), 'rch_jwt_user')) {
        return parent::onKernelRequest($event);
    }
}
```
to ensure only the content of requests concerning a route of this bundle will be converted.
What do you think? Would you be motivated to work on this? so you can btw revert what has been done here, plus you deserve the credits of the feature.

**Comment by cve** [comment]
I'm 100% agree with you. I will try to make changes later

**Comment by chalasr** [comment]
Just a thing thought, could you open your PR on the `1.x` branch? So I can tag a minor `v1.3.1` then merge it into the master branch. Thank you in advance! Looking forward a PR from you.

**Comment by cve** [comment]
Ok,

I'm try to install 1.3 from https://github.com/chalasr/rchjwtuserbundle/tree/1.x guide but it seems that this Readme is for 2.0 branch and I have errors during install it on fresh symfony 2.8

**Comment by chalasr** [comment]
Could you please open an issue to develop what kind of problem you encounter?

**Comment by cve** [comment]
Sorry, correct me if I'm wrong... I understood that I should make above changes (listener etc.) to the 1.x branch... So I'm clone that branch and try to install on the fresh Symfony 2.8 and I have errors... this is the issue I've created about it #11

**Pull request merged**
